version: 2.1

jobs:
  waterfox-classic-build_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install flatpak
      - run: ./build.sh net.waterfoxco.waterfox-classic
  waterfox-g4-build_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install flatpak
      - run: ./build.sh net.waterfoxco.waterfox-g4

workflows:
  say-hello-workflow:
    jobs:
      - waterfox-classic-build_test
      - waterfox-g4-build_test
