version: 2.1

jobs:
  waterfox-classic-build_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install flatpak curl
      - run: curl https://sh.rustup.rs -sSf | sh
      - run: ./setup_runtime.sh
      - run: ./build.sh net.waterfoxco.waterfox-classic
  waterfox-g4-build_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install flatpak curl
      - run: curl https://sh.rustup.rs -sSf | sh
      - run: ./setup_runtime.sh
      - run: ./build.sh net.waterfoxco.waterfox-g4

workflows:
  waterfox-g4-workflow:
    jobs:
      - waterfox-classic-build_test
  waterfox-classic-workflow:
    jobs:
      - waterfox-g4-build_test
